// Prometheus metrics for Bimbles
import { collectDefaultMetrics, Counter, Gauge, Registry } from 'prom-client';

// Single shared registry — everything lands here
export const registry = new Registry();

// Enable default metrics (CPU, memory, event loop, etc.)
collectDefaultMetrics({ register: registry });

// Active game rooms
export const activeRooms = new Gauge({
  name: 'bimbles_active_rooms',
  help: 'Number of active game rooms',
  registers: [registry],
});

// Active WebSocket connections
export const activeConnections = new Gauge({
  name: 'bimbles_active_connections',
  help: 'Number of active WebSocket connections',
  registers: [registry],
});

// AI generation requests
export const aiRequests = new Counter({
  name: 'bimbles_ai_requests_total',
  help: 'Total AI generation requests',
  labelNames: ['model', 'status'] as const,
  registers: [registry],
});

// Rooms created
export const roomCreations = new Counter({
  name: 'bimbles_rooms_created_total',
  help: 'Total rooms created',
  labelNames: ['mode'] as const,
  registers: [registry],
});

// Questions generated by AI
export const questionsGenerated = new Counter({
  name: 'bimbles_questions_generated_total',
  help: 'Total questions generated by AI',
  labelNames: ['type'] as const,
  registers: [registry],
});
