// Prometheus metrics for Bimbles
import { collectDefaultMetrics, Counter, Gauge, Registry } from 'prom-client';

// Single registry for all metrics
export const registry = new Registry();

// Enable default metrics (CPU, memory, etc.)
collectDefaultMetrics({ register: registry });

// Custom metrics
export const activeRooms = new Gauge({
  name: 'bimbles_active_rooms',
  help: 'Number of active game rooms',
  labelNames: [],
  registers: [registry],
});

export const activeConnections = new Gauge({
  name: 'bimbles_active_connections',
  help: 'Number of active WebSocket connections',
  labelNames: [],
  registers: [registry],
});

export const aiRequests = new Counter({
  name: 'bimbles_ai_requests_total',
  help: 'Total AI generation requests',
  labelNames: ['model', 'status'],
  registers: [registry],
});

export const roomCreations = new Counter({
  name: 'bimbles_rooms_created_total',
  help: 'Total rooms created',
  labelNames: ['mode'],
  registers: [registry],
});

export const questionsGenerated = new Counter({
  name: 'bimbles_questions_generated_total',
  help: 'Total questions generated by AI',
  labelNames: ['type'],
  registers: [registry],
});
